ToMyongJi/ToMyongJi-front

src/pages/login/Login.jsx, src/pages/login/SignUp.jsx, src/utils/authApi.js
> #59 
> api 변경에 따른 로그인, 회원가입 오류 해결
=> Fix: 회원가입 오류 해결

src/pages/receipt/CreateReceipt.jsx
=> Fix: 영수증 작성 userId 수정

src/pages/login/SignUp.jsx
> #63 
> 회원가입시 발생한 자격 설정 및 대학 선택 오류 수정
=> Fix: 자격 및 대학 선택 오류 수정

src/pages/MyPage.jsx, src/pages/admin/Admin.jsx, src/utils/studentClubMemberApi.js
> #64 
> 마이페이지 소속부원 추가 및 삭제, 어드민 소속부원 추가 및 삭제 오류 수정
=> Fix: 마이페이지 소속부원 추가 및 삭제, 어드민 소속부원 추가 및 삭제 오류 수정

src/pages/login/Find.jsx
=> Fix: 아이디 찾기 오류 수정

src/pages/admin/Admin.jsx
> #63 
> adim 페이지 회장 변경 오류 메세지 수정
=> Fix: adim 페이지 회장 변경 오류 메세지 수정

src/pages/login/SignUp.jsx, src/utils/authApi.js
> #63 
> 소속인증 api GET 요청에서 POST 요청으로 수정. 
> 기존에 path variable -> request body에 clubId, studentNum, role
=> Fix: 회원가입 소속인증 요청 수정

src/pages/MyPage.jsx, src/pages/login/Login.jsx, src/pages/receipt/CreateReceipt.jsx, src/store/authStore.js, src/utils/adminApi.js, src/utils/api.js, src/utils/authApi.js, src/utils/receiptApi.js, src/utils/studentClubMemberApi.js
> #63 
> security config 후 토큰 문제 해결
=> Hotfix: security config 후 발생하는 토큰 문제 해결

src/pages/login/SignUp.jsx
> #63 
> admin 페이지 레이아웃 수정 및 회원가입 필드 수정
=> Fix: admin 페이지 레이아웃 수정 및 회원가입 필드 수정

src/App.jsx
=> Fix: 토큰 만료 시간에 따른 로그아웃 처리

package.json, src/App.jsx, src/pages/receipt/CreateReceipt.jsx
=> Fix: OCR 버튼 주석 처리

package.json, src/App.jsx
> #63 
> 방문자수 분석을 위한 vercel anayltics
- npm i @vercel/analytics을 통한 모듈 설치
- 최상단 App.jsx에 <Analytics/> 추가
=> Feat: 방문자수 분석을 위한 vercel anayltics

src/pages/login/Login.jsx
=> Hotfix: Admin 라우팅 수정

package.json, src/pages/receipt/CreateReceipt.jsx, src/pages/receipt/ReceiptsList.jsx
> #78 
> 영수증 기간별 조회 -> 월별 조회로 수정
- 사용자들의 피드백을 바탕으로 월별 조회로 수정
=> Fix: 영수증 기간별 조회 -> 월별 조회로 수정

src/App.jsx, src/pages/Maintenance.jsx
> #78 
> 점검을 위한 페이지 추가 및 기간 설정 라우팅
- Maintenance 페이지
- App.jsx에서 기간 설정 라우팅 추가
=> Feat: 점검을 위한 페이지 추가 및 기간 설정 라우팅

src/pages/admin/Admin.jsx, src/pages/login/SignUp.jsx
> #78 
> email 인증 alert 창 수정 및 admin 학생 정보 조회 렌더링 수정
- 이메일 전송 alert창이 바로 뜨게 수정
- admin에서 학생 정보 조회 렌더링 시 새로고침해야 조회가능한 이슈 해결
=> Fix: email 인증 alert 창 수정 및 admin 학생 정보 조회 렌더링 수정

src/App.jsx, src/pages/Maintenance.jsx, src/pages/login/Login.jsx, src/pages/receipt/CreateReceipt.jsx, src/pages/receipt/ReceiptsList.jsx, src/utils/receiptApi.js
> #78 
> Hotfix: 서버 점검 알림 화면
- api 설계 오류로 인한 4/13 15:00 ~ 4/14 00:00 서버 점검
=> Hotfix: 서버 점검 알림 화면

src/App.jsx, src/pages/login/Login.jsx
> #78 
> hotfix: 점검 종료 및 영수증 조회 수정
- 영수증 조회시 잔액은 학생회 소속만 보이게 수정
- 일반 유저는 잔액이 안보임
- 로그인 토큰 부분 수정
=> hotfix: 점검 종료 및 영수증 조회 수정

src/pages/receipt/CreateReceipt.jsx, src/pages/receipt/ReceiptsList.jsx, src/utils/receiptApi.js
> #78 
> 영수증 csv 추출 및 연/월 조회 기능 추가
- 사용자 피드백을 바탕으로 영수증 내역 추출 및 연/월 조회 기능 추가
=> Feat: 영수증 csv 추출 및 연/월 조회 기능 추가

src/pages/login/SignUp.jsx
> #78 
> 회원가입 관련 요청시 또는 요청 완료시 버튼 비활성화
- 사용자들이 회원가입 관련 버튼을 1번 이상 클릭시 요청이 1번 이상가서 문제가 발생
- 요청중 또는 요청 완료시 버튼 disabled
=> Fix: 회원가입 관련 요청시 또는 요청 완료시 버튼 비활성화

src/pages/receipt/UploadCSVReceipt.jsx
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 테스트 결과나 스크린 샷으로 보여줘야하는 부분을 삽입해주세요,
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> fix: CSV 안내 멘트 추가

src/pages/receipt/CreateReceipt.jsx, src/utils/receiptApi.js
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 테스트 결과나 스크린 샷으로 보여줘야하는 부분을 삽입해주세요,
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> 영수증 수정기능 추가 후 배포

src/pages/receipt/CreateReceipt.jsx, src/utils/receiptApi.js
Close #100 
수기로 입금 / 출금 동시 저장 시 안내 멘트 수정
=> Feat/alert modifying #100

src/pages/receipt/UploadTossReceipt.jsx
=> feat: toss 거래내역서 업로드 api 연결

src/pages/receipt/UploadTossReceipt.jsx
=> 거래내역서 업로드 방법 멘트 수정

src/pages/MyPage.jsx, src/pages/receipt/ReceiptsList.jsx
=> Fix/doubleclick #106
